# Generated by Django 4.1.5 on 2023-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=20, verbose_name='Title')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
